# Generated by Django 5.2.8 on 2026-01-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_question_type_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
