# Generated by Django 5.2.8 on 2026-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='course',
            name='per_question_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
