# Generated by Django 5.2.8 on 2026-02-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_course_duration_minutes_course_per_question_seconds'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('per_question_seconds', models.PositiveIntegerField(default=60)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exambundle'),
        ),
    ]
