# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_result_unique_student_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambundle',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='When the exam window opens (use admin Manage Exams to set).', null=True),
        ),
        migrations.AddField(
            model_name='exambundle',
            name='schedule_duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='How many hours the exam stays open after the start time.', null=True),
        ),
    ]
