# Generated by Django 6.0.3 on 2026-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_remove_result_unique_student_course_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambundle',
            name='exam_type',
            field=models.CharField(choices=[('mid', 'Mid Exam'), ('final', 'Final Exam')], default='mid', max_length=10),
        ),
    ]
