# Generated by Django 5.2.8 on 2026-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_exambundle_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
