# Generated by Django 5.2.8

from django.db import migrations, models


def set_student_ids(apps, schema_editor):
    Student = apps.get_model('student', 'Student')
    for s in Student.objects.all():
        if not s.student_id:
            s.student_id = f"STU{str(s.id).zfill(5)}"
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(set_student_ids, migrations.RunPython.noop),
    ]
